Add missing includes of the supports mixin
Fixes errors seen when spec/automated_review/ar_models_must_have_tables_spec.rb
is run in the core repository with rails 6:

```
NoMethodError:
  undefined method `supports' for #<Class:0x00007ffbb23f3120>
  Did you mean?  suppress
```